spring:
  profiles:
#  开发使用此配置
    active: dev
#    打包使用此配置
#    active: test
#datasource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 3
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#http
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  redis:
    jedis:
      pool:
        max-idle: 30
        max-active: 6000
  servlet:
    #文件上传配置：10MB
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#mybaits
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.newlife.charge.core
  mapper-locations: classpath:mappers/*.xml
#log
logging:
  config: classpath:config/logback.xml

page:
   pageSize: 20

jwt:
  secret: $#@!mseenet!@#$

sms:
  server:
    ip: app.cloopen.com
    port: 8883
  account:
    sid: 8a216da85d158d1b015d63e2ce3e21b7
    token: 544d3f8e851c4279b1a7fa076bee7b02
  appid: 8aaf07085d106c7f015d63efb11b24b5

headImg:
   teacher: /upload/avatarImg/teacher.png
   student: /upload/avatarImg/student.png
   admin: /upload/avatarImg/admin.png

#huanxing
easemob:
  orgname: 273535049
  appname: hxfirst
  password_key: mseenet.com
  clientid: YXA6LM-N8G6OEeaYIR3xUTc7Xg
  client_secret: YXA64pJ-tw1DEPlHsmwkTydPUern68M
  grant_type: client_credentials


